### ISSUE TITLE
Xur method error

### ISSUE THREAD

**Issue by IanMcNelly** [PDaily/destiny_rb#2]
When calling xur on the client, (i.e. client.xur) if xur is not in the tower, instead of returning not found or nil, we get an error undefined method '[]' for nil nilclass.

This is due to line 11 in vendors.rb, which should read:

```
 elsif raw_data.empty? || raw_data.nil?
```

I am submitting this issue to match a PR I will submit soon.

**Comment by pdai1y** [comment]
Awesome, thank you for catching that!
